// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InnerMessage.proto

package com.sunny.jmh.serializertest.bean.protobuf;
/**
 * <Description> <br>
 *
 * @author Sunny<br>
 * @version 1.0<br>
 * @taskId: <br>
 * @createDate 2018/12/05 0:30 <br>
 * @see com.sunny.jmh.serializertest.bean.protobuf <br>
 */
public final class InnerMessageProtos {
  private InnerMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InnerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sunny.jmh.serializertest.bean.protobuf.InnerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    String getName();
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    boolean hasType();
    /**
     * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType getType();
  }
  /**
   * Protobuf type {@code com.sunny.jmh.serializertest.bean.protobuf.InnerMessage}
   */
  public  static final class InnerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sunny.jmh.serializertest.bean.protobuf.InnerMessage)
      InnerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InnerMessage.newBuilder() to construct.
    private InnerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerMessage() {
      name_ = "name";
      id_ = 0;
      type_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InnerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType value = com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.internal_static_com_github_bean_protobuf_InnerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.internal_static_com_github_bean_protobuf_InnerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage.class, com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1 [default = "name"];</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
     */
    public com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType getType() {
      com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType result = com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType.valueOf(type_);
      return result == null ? com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType.UNIVERSAL : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage)) {
        return super.equals(obj);
      }
      com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage other = (com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sunny.jmh.serializertest.bean.protobuf.InnerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sunny.jmh.serializertest.bean.protobuf.InnerMessage)
        com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.internal_static_com_github_bean_protobuf_InnerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.internal_static_com_github_bean_protobuf_InnerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage.class, com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage.Builder.class);
      }

      // Construct using com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "name";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.internal_static_com_github_bean_protobuf_InnerMessage_descriptor;
      }

      public com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage getDefaultInstanceForType() {
        return com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage.getDefaultInstance();
      }

      public com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage build() {
        com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage buildPartial() {
        com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage result = new com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage) {
          return mergeFrom((com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage other) {
        if (other == com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "name";
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1 [default = "name"];</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType getType() {
        com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType result = com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType.valueOf(type_);
        return result == null ? com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType.UNIVERSAL : result;
      }
      /**
       * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public Builder setType(com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.EnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.sunny.jmh.serializertest.bean.protobuf.EnumType type = 3 [default = UNIVERSAL];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sunny.jmh.serializertest.bean.protobuf.InnerMessage)
    }

    // @@protoc_insertion_point(class_scope:com.sunny.jmh.serializertest.bean.protobuf.InnerMessage)
    private static final com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage();
    }

    public static com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<InnerMessage>
        PARSER = new com.google.protobuf.AbstractParser<InnerMessage>() {
      public InnerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InnerMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InnerMessage> getParserForType() {
      return PARSER;
    }

    public com.sunny.jmh.serializertest.bean.protobuf.InnerMessageProtos.InnerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_bean_protobuf_InnerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_bean_protobuf_InnerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022InnerMessage.proto\022\030com.sunny.jmh.serializertest.bean.pr" +
      "otobuf\032\016EnumType.proto\"k\n\014InnerMessage\022\022" +
      "\n\004name\030\001 \001(\t:\004name\022\n\n\002id\030\002 \001(\005\022;\n\004type\030\003" +
      " \001(\0162\".com.sunny.jmh.serializertest.bean.protobuf.EnumType" +
      ":\tUNIVERSALB.\n\030com.sunny.jmh.serializertest.bean.protobufB" +
      "\022InnerMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.getDescriptor(),
        }, assigner);
    internal_static_com_github_bean_protobuf_InnerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_bean_protobuf_InnerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_bean_protobuf_InnerMessage_descriptor,
        new String[] { "Name", "Id", "Type", });
    com.sunny.jmh.serializertest.bean.protobuf.EnumTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
