/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sunny.jmh.serializertest.bean.avro;
/**
 * <Description> <br>
 *
 * @author Sunny<br>
 * @version 1.0<br>
 * @taskId: <br>
 * @createDate 2018/12/05 0:30 <br>
 * @see com.sunny.jmh.serializertest.bean.avro <br>
 */
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EnumTypeAvro {
  UNIVERSAL, WEB, IMAGES, LOCAL, NEWS, PRODUCTS, VIDEO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnumTypeAvro\",\"namespace\":\"com.sunny.jmh.serializertest.bean.avro\",\"symbols\":[\"UNIVERSAL\",\"WEB\",\"IMAGES\",\"LOCAL\",\"NEWS\",\"PRODUCTS\",\"VIDEO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
